# Generated by Django 5.1.1 on 2024-09-16 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nastamba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vrsta', models.CharField(choices=[('Mračna', 'Mračna'), ('Grijana', 'Grijana'), ('Osunčana', 'Osunčana')], max_length=50)),
                ('ime', models.CharField(blank=True, max_length=100, null=True)),
                ('centralna_tocka_lat', models.FloatField()),
                ('centralna_tocka_lng', models.FloatField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('biljke', models.TextField(blank=True, null=True)),
                ('stabla', models.TextField(blank=True, null=True)),
                ('sekundarne_zivotinje', models.TextField(blank=True, null=True)),
                ('evidencija_prisutnosti', models.BooleanField(default=False)),
                ('je_aktivna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('prezime', models.CharField(max_length=255)),
                ('kontakt', models.CharField(max_length=255)),
                ('obrazovanje', models.CharField(max_length=255)),
                ('sposobnost', models.CharField(max_length=255)),
                ('rok_trajanja_kvalifikacija', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zadatak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KalendarRada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('dostupnost', models.CharField(choices=[('Dostupan', 'Dostupan'), ('Na odmoru', 'Na odmoru'), ('Bolovanje', 'Bolovanje')], max_length=15)),
                ('radnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zooloski.radnik')),
            ],
        ),
        migrations.CreateModel(
            name='GrupnaPosjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('broj_posjetitelja', models.IntegerField()),
                ('vodic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Zooloski.radnik')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('obavljen', models.BooleanField()),
                ('zadatak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zooloski.zadatak')),
            ],
        ),
        migrations.CreateModel(
            name='Zivotinja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrvatski_naziv', models.CharField(max_length=255)),
                ('latinski_naziv', models.CharField(max_length=255)),
                ('engleski_naziv', models.CharField(max_length=255)),
                ('ime', models.CharField(blank=True, max_length=255, null=True)),
                ('broj', models.IntegerField(blank=True, null=True)),
                ('porijeklo', models.CharField(choices=[('Kupovina', 'Kupovina'), ('Donacija', 'Donacija'), ('Rođenje', 'Rođenje')], max_length=50)),
                ('datum_nastanka', models.DateField()),
                ('arhiviran', models.BooleanField(default=False)),
                ('nastamba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Zooloski.nastamba')),
            ],
        ),
        migrations.CreateModel(
            name='Trosak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255)),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
                ('zivotinja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zooloski.zivotinja')),
            ],
        ),
        migrations.CreateModel(
            name='Obaveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_obaveze', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Obavljeno', 'Obavljeno'), ('Zakazano', 'Zakazano')], max_length=10)),
                ('datum', models.DateField()),
                ('komentari', models.TextField(blank=True, null=True)),
                ('zivotinja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zooloski.zivotinja')),
            ],
        ),
        migrations.CreateModel(
            name='Nezgoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=255)),
                ('utjecaj', models.TextField()),
                ('komentari', models.TextField(blank=True, null=True)),
                ('trosak_sanacije', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
                ('nastamba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zooloski.nastamba')),
                ('zivotinja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zooloski.zivotinja')),
            ],
        ),
    ]
